version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: im-legal
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://variable:HxH787898HxH@hunter.com@im-legal-db:5432/im-legal-db?schema=public
      - REDIS_HOST=im-legal-redis
      - S3_HOST=im-legal-s3
    networks:
      - im-legal
    volumes:
      - ./.env:/app/.env
    depends_on:
      - im-legal-redis
      - im-legal-s3
      - api-migration
  api-migration:
      build:
        context: .
        dockerfile: Dockerfile.migrate
      entrypoint: "npm run migrate:run"
      restart: "no"
      environment:
        - DATABASE_URL=postgresql://variable:HxH787898HxH@hunter.com@im-legal-db:5432/im-legal-db?schema=public
      networks:
        - im-legal
      volumes:
        - ./.env:/app/.env
      depends_on:
        - db
  im-legal-redis:
    image: redis
    container_name: im-legal-redis-store
    restart: always
    ports:
      - "6379:6379"
    networks:
      - im-legal
    volumes:
      - im-legal-redis_data:/data
    command: redis-server --appendonly yes
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
  im-legal-s3:
    image: 'bitnami/minio:latest'
    container_name: im-legal-s3-store
    ports:
      - '9000:9000'
      - '9001:9001'
    restart: always
    environment:
      - MINIO_ROOT_USER=ROOTNAME
      - MINIO_ROOT_PASSWORD=CHANGEME123
    networks:
      - im-legal
    volumes:
      - im-legal-s3:/data
  db:
    image: postgres
    container_name: im-legal-db
    ports:
      - '5432:5432'
    networks:
      - im-legal
    restart: always
    environment:
      - POSTGRES_PASSWORD=HxH787898HxH@hunter.com
      - POSTGRES_USER=variable
      - POSTGRES_DB=im-legal-db

networks:
  im-legal:
    driver: bridge

volumes:
  im-legal-s3:
  im-legal-redis_data:
